README.md, cameraview/build.gradle
=> Bump version

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/views/com/otaliastudios/cameraview/ScrollGestureLayout.java
=> Fix vertical scrolls, removed some logs

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
Add float casting before computing ratio
=> Fix bug with measuring behavior

README.md, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, demo/src/main/java/com/otaliastudios/cameraview/demo/MainActivity.java
Location is now backed by `Location` platform class. Fixes #6 .
=> Fix location bug, add setLocation(Location)

README.md, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/Mapper.java, cameraview/src/main/options/com/otaliastudios/cameraview/Hdr.java, cameraview/src/main/res/values/attrs.xml, cameraview/src/main/utils/com/otaliastudios/cameraview/CameraUtils.java
Adds HDR support (enabling disabling for now) for devices that support it.
=> HDR support

cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/utils/com/otaliastudios/cameraview/OrientationHelper.java, cameraview/src/main/utils/com/otaliastudios/cameraview/WorkerHandler.java, cameraview/src/main/views/com/otaliastudios/cameraview/Preview.java
- improve threading by delegating to CameraController
- ensure start and stop calls are executed in a worker thread
- add `CameraOptions.supports()` to easily check what's supported
- other minor changes
=> Improve threading, add CameraOptions.supports()

.travis.yml, README.md, cameraview/build.gradle, cameraview/src/androidTest/java/com/otaliastudios/cameraview/AspectRatioTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraOptions1Test.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/ExtraProperties1Test.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/Mapper1Test.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockPreview.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/views/com/otaliastudios/cameraview/GestureLayout.java
Add some instrumentation tests.
=> Add instrumentation tests

README.md, build.gradle, cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/options/com/otaliastudios/cameraview/Audio.java, cameraview/src/main/res/values/attrs.xml, demo/src/main/res/layout/activity_main.xml
In my application I have one important feature, user can enable or disable audio stream before start video recording. I added it like a HDR and if you like this idea, I will add this feature to documentation. 
Thanks!
=> Added audio on/off feature for video recording

cameraview/src/main/res/layout/surface_view.xml, cameraview/src/main/res/layout/texture_view.xml, cameraview/src/main/views/com/otaliastudios/cameraview/SurfaceCameraPreview.java, cameraview/src/main/views/com/otaliastudios/cameraview/TextureCameraPreview.java
I had introduced a regression somewhere, fixes #57
=> Ensure Grid and focus markers are shown

LICENSE, README.md
- Add license info for the original project we are a fork of
- Relicense additional work to MIT for consistency and simplicity
=> Add license info

build.gradle
Updated supportLibVersion to 26.1.0 in Gradle.
Built successfully in Android Studio 3.0 RC 2.
=> Update to supportLibVersion 26.1.0

README.md, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraLoggerTest.java, cameraview/src/main/utils/com/otaliastudios/cameraview/CameraLogger.java
Add the ability to inject external loggers for internal events.
=> Inject external loggers

ISSUE_TEMPLATE.md, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
=> Release PreviewCallback during stop events

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
=> Avoid ConcurrentModificationExceptions in listeners

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraOptions1Test.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewCallbacksTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/OrientationHelperTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/Size.java, cameraview/src/main/utils/com/otaliastudios/cameraview/OrientationHelper.java, cameraview/src/test/java/com/otaliastudios/cameraview/SizeTest.java
- Add `CameraOptions.getSupportedPictureSizes()`
- Add `CameraOptions.getSupportedPictureAspectRatios()`
- Cleanup useless stuff
=> Improve CameraOptions APIs, cleanup

cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
=> Check focus area max number before applying

demo/src/main/AndroidManifest.xml
=> Demo app: lock orientation to a fixed value

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/views/com/otaliastudios/cameraview/GestureLayout.java, cameraview/src/main/views/com/otaliastudios/cameraview/PinchGestureLayout.java, cameraview/src/main/views/com/otaliastudios/cameraview/ScrollGestureLayout.java
=> Add discrete granularity to pinch and scroll events

README.md, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/res/values/attrs.xml
Fixes #65 (it's the best we can do)
=> Add setVideoMaxDuration() API

cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
=> Reset flags when stopping camera

cameraview/src/main/utils/com/otaliastudios/cameraview/OrientationHelper.java
=> Prevent context leak through SystemSensorManager #242

cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
Improved #304 to go on with a new release, thanks @stefanJi
=> Restore frame processor after videos

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraOptions1Test.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewCallbacksTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, docs/_posts/2018-12-20-runtime-permissions.md
Fixes #350 
Fixes #355 
Fixes #357
=> V2 bug fixes

cameraview/src/androidTest/java/com/otaliastudios/cameraview/PictureResultTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/VideoResultTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/PictureResult.java, cameraview/src/main/java/com/otaliastudios/cameraview/SnapshotPictureRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/VideoResult.java, codecov.yml
- Fixes #15 
- Fixes #287 
- Tests: yes
=> Flip snapshots, add PictureResult.getFacing and VideoResult.getFacing

cameraview/src/main/gles/com/otaliastudios/cameraview/AudioMediaEncoder.java, cameraview/src/main/gles/com/otaliastudios/cameraview/ByteBufferPool.java, cameraview/src/main/gles/com/otaliastudios/cameraview/EglBaseSurface.java, cameraview/src/main/gles/com/otaliastudios/cameraview/EglCore.java, cameraview/src/main/gles/com/otaliastudios/cameraview/InputBuffer.java, cameraview/src/main/gles/com/otaliastudios/cameraview/InputBufferPool.java, cameraview/src/main/gles/com/otaliastudios/cameraview/MediaCodecBuffers.java, cameraview/src/main/gles/com/otaliastudios/cameraview/MediaEncoder.java, cameraview/src/main/gles/com/otaliastudios/cameraview/MediaEncoderEngine.java, cameraview/src/main/gles/com/otaliastudios/cameraview/OutputBuffer.java, cameraview/src/main/gles/com/otaliastudios/cameraview/OutputBufferPool.java, cameraview/src/main/gles/com/otaliastudios/cameraview/Pool.java, cameraview/src/main/gles/com/otaliastudios/cameraview/TextureMediaEncoder.java, cameraview/src/main/gles/com/otaliastudios/cameraview/VideoMediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/SnapshotVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/VideoRecorder.java, cameraview/src/main/utils/com/otaliastudios/cameraview/WorkerHandler.java, demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java
=> Improve snapshot recording

README.md, build.gradle, cameraview/build.gradle, cameraview/src/main/gles/com/otaliastudios/cameraview/EglCore.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, demo/build.gradle, demo/src/main/AndroidManifest.xml, docs/_posts/2018-12-20-changelog.md, docs/_posts/2018-12-20-install.md
Fixes #377, #384 and bumps version.
=> v2.0.0-beta03

.travis.yml, cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/Frame.java, cameraview/src/main/java/com/otaliastudios/cameraview/FrameManager.java, cameraview/src/test/java/com/otaliastudios/cameraview/FrameManagerTest.java, cameraview/src/test/java/com/otaliastudios/cameraview/FrameTest.java, demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java
Fixes #429 and a freeze() / release() bug described in #423.
=> Fix processor OOM bug

README.md, cameraview/build.gradle, cameraview/src/androidTest/java/com/otaliastudios/cameraview/VideoRecorderTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/FullVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/SnapshotPictureRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/SnapshotVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/VideoRecorder.java, docs/_posts/2018-12-20-changelog.md, docs/_posts/2018-12-20-install.md
Fixes a few bug and bumps version.
=> Quick fixes & bump version

cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java
- checked whether the zoom and exposer functionality is present or not.
- implemented zoom in CameraEngine2
references
https://developer.android.com/reference/android/hardware/camera2/CameraCharacteristics
https://stackoverflow.com/questions/32711975/zoom-camera2-preview-using-textureview
=> Camera2 Zoom and Exposure implemetation

README.md, cameraview/build.gradle, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/frame/FrameManager.java, cameraview/src/main/java/com/otaliastudios/cameraview/picture/PictureRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/preview/CameraPreview.java, cameraview/src/main/java/com/otaliastudios/cameraview/preview/GlCameraPreview.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/Full2VideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/VideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/MediaEncoder.java, docs/_posts/2018-12-20-changelog.md, docs/_posts/2018-12-20-install.md
This release includes breaking changes and important new features - above all, a complete Camera2 integration.
=> Release version 2.0.0-beta06

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/preview/MockCameraPreview.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Step.java, cameraview/src/main/java/com/otaliastudios/cameraview/picture/SnapshotGlPictureRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/preview/CameraPreview.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/Full2VideoRecorder.java, cameraview/src/main/res/values/attrs.xml, demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java, demo/src/main/java/com/otaliastudios/cameraview/demo/Control.java, demo/src/main/res/layout/activity_camera.xml, docs/_posts/2018-12-20-changelog.md, docs/_posts/2018-12-20-more-features.md, docs/_posts/2018-12-20-previews.md
- Fixes #379 
- Tests: yes
- Docs updated: yes
=> Use device orientation flag

build.gradle, cameraview/build.gradle
=> Fix pom file not containing dependencies

cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/MockCameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/egl/EglBaseSurface.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/utils/CropHelper.java, cameraview/src/main/java/com/otaliastudios/cameraview/picture/SnapshotGlPictureRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/size/AspectRatio.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/TextureMediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/VideoMediaEncoder.java, demo/src/main/AndroidManifest.xml, demo/src/main/java/com/otaliastudios/cameraview/demo/PicturePreviewActivity.java, demo/src/main/java/com/otaliastudios/cameraview/demo/VideoPreviewActivity.java, demo/src/main/res/layout/activity_camera.xml
=> Small fixes

cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/CameraIntegrationTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/internal/utils/WorkerHandlerTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/overlay/OverlayDrawerTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/Issue514Workaround.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/egl/EglViewport.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/utils/WorkerHandler.java, cameraview/src/main/java/com/otaliastudios/cameraview/overlay/OverlayDrawer.java, cameraview/src/main/java/com/otaliastudios/cameraview/picture/SnapshotGlPictureRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/TextureConfig.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/TextureMediaEncoder.java, demo/src/main/res/layout/activity_camera.xml
- Fixes #514
- Improves picture snapshot recorder
- Improves thread management
=> Fix issue 514

README.md, cameraview/src/androidTest/java/com/otaliastudios/cameraview/video/VideoRecorderTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/utils/WorkerHandler.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/FullVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/VideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/AudioConfig.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/AudioMediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/AudioNoise.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/MediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/MediaEncoderEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/TextureMediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/VideoMediaEncoder.java, demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java, demo/src/main/res/layout/activity_camera.xml
- Improves audio recording
- Improves video recording by dropping frames
- Fixes video snapshot exception
=> Improve video snapshots

cameraview/src/androidTest/java/com/otaliastudios/cameraview/BaseEglTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/filter/BaseFilterTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/filter/FiltersTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/filter/NoFilterTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/filter/SimpleFilterTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/overlay/OverlayDrawerTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/BaseFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/NoFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/SimpleFilter.java, docs/_posts/2019-08-06-filters.md
- Adds `SimpleFilter` for creating simple filters without subclassing
- Tests for the `filter` package
=> Add SimpleFilter

cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/CameraIntegrationTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/AudioMediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/MediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/MediaEncoderEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/TextureMediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/VideoMediaEncoder.java
- Fix `takeVideoSnapshot` not working unless you set a max duration (Fixes #553)
- Fix video recording causing crashes on some devices (Fixes #549)
=> Video bugs

cameraview/src/androidTest/java/com/otaliastudios/cameraview/internal/DeviceEncodersTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/BaseFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/Filter.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/DeviceEncoders.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/FullVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/AudioConfig.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/AudioMediaEncoder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/VideoConfig.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/VideoMediaEncoder.java, docs/_posts/2019-02-24-snapshot-size.md
- Checks encoders using `MediaCodecList`, preferring hardware accelerated encoders over the software ones
- Aligns width, height and bitRate based on codec requirements.
Fixes #534
Fixes #548
=> Encoders improvements

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, demo/src/main/res/layout/activity_camera.xml
=> Fix layout editor preview

cameraview/src/androidTest/java/com/otaliastudios/cameraview/filter/MultiFilterTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/MultiFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/egl/EglViewport.java, cameraview/src/main/java/com/otaliastudios/cameraview/picture/SnapshotGlPictureRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/preview/GlCameraPreview.java, cameraview/src/main/java/com/otaliastudios/cameraview/preview/RendererFrameCallback.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/encoding/TextureMediaEncoder.java, demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java, docs/_posts/2019-08-06-filters.md
=> MultiFilter to merge filters

cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/CameraIntegration2Test.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/CameraIntegrationTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/frame/FrameManagerTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/gesture/ScrollGestureFinderTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/frame/Frame.java, cameraview/src/main/java/com/otaliastudios/cameraview/frame/FrameManager.java, cameraview/src/main/java/com/otaliastudios/cameraview/picture/Snapshot1PictureRecorder.java, cameraview/src/test/java/com/otaliastudios/cameraview/frame/FrameManagerTest.java, cameraview/src/test/java/com/otaliastudios/cameraview/frame/FrameTest.java, docs/_posts/2018-12-20-frame-processing.md
Improvements to frame processing should fix some crashes or at least give clear messages about what's happening.
Fixes #544
Fixes #554
=> Frame improvements

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraOptions1Test.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/DeviceEncoders.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/utils/CamcorderProfiles.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/Full1VideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/Full2VideoRecorder.java, cameraview/src/main/java/com/otaliastudios/cameraview/video/FullVideoRecorder.java
=> takeVideo improvements

.github/FUNDING.yml, README.md, docs/_posts/2018-12-21-donate.md
=> GitHub Sponsors links

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/CameraIntegrationTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/MockCameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/res/values/attrs.xml
Added Support for 60fps for Camera2Engine
- Tests: ... (*yes*)
- Docs updated: ... (*no*)
First we find if the camera supports higher frame rate, which is given to us by Range. If it does we take videosnapshot with higher frame rate
=> added support for higher frame rate

README.md, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraOptions1Test.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java, demo/src/main/java/com/otaliastudios/cameraview/demo/Option.java, docs/_posts/2018-12-20-controls.md
Add docs for #653 + adds support for Camera1.
=> Preview FPS docs + Camera1 implementation

README.md, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/preview/GlCameraPreview.java, cameraview/src/main/res/values/attrs.xml, docs/_config.yml, docs/_layouts/page.html, docs/_posts/2018-12-20-changelog.md, docs/_posts/2018-12-20-runtime-permissions.md, docs/css/main.css, docs/css/syntax.css, docs/index.md
Adds `cameraRequestPermissions="true|false"` to enable or disable the automatic permission requests.
=> Permission flag

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/MockCameraEngine.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/metering/MeteringRegionsTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/meter/MeterAction.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/metering/Camera1MeteringTransform.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/metering/Camera2MeteringTransform.java, cameraview/src/main/java/com/otaliastudios/cameraview/metering/MeteringRegion.java, cameraview/src/main/java/com/otaliastudios/cameraview/metering/MeteringRegions.java, cameraview/src/main/java/com/otaliastudios/cameraview/metering/MeteringTransform.java, docs/_posts/2018-12-20-changelog.md, docs/_posts/2019-09-04-metering.md
Adds a new metering API which takes in a `RectF` instead of a point.
=> Add startAutoFocus(Rect)

.github/workflows/build.yml, cameraview/build.gradle, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/meter/ExposureMeter.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/DeviceEncoders.java
- Increase metering timeout for touch metering: 2.5 seconds not enough on some devices
- Fix some "Encoder not found" crashes
- Extend touch metering to legacy devices
=> Metering improvements

cameraview/src/androidTest/java/com/otaliastudios/cameraview/frame/ByteBufferFrameManagerTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/frame/FrameManagerTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/BaseFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/Filter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filter/MultiFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/AutoFixFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/BrightnessFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/ContrastFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/DocumentaryFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/DuotoneFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/FillLightFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/GammaFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/GrainFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/HueFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/LomoishFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/SaturationFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/SharpnessFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/TemperatureFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/TintFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/filters/VignetteFilter.java, cameraview/src/main/java/com/otaliastudios/cameraview/frame/ByteBufferFrameManager.java, cameraview/src/main/java/com/otaliastudios/cameraview/frame/Frame.java, cameraview/src/main/java/com/otaliastudios/cameraview/frame/FrameManager.java, cameraview/src/main/java/com/otaliastudios/cameraview/picture/Snapshot1PictureRecorder.java, cameraview/src/test/java/com/otaliastudios/cameraview/frame/FrameTest.java, docs/_docs/frame-processing.md
- Add frame.rotationToView
- Add frame.rotationToUser
- Deprecate frame.rotation
=> Frame rotation improvements

README.md, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/MockCameraEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, cameraview/src/main/res/values/attrs.xml, docs/_docs/controls.md
Unless this is a simple fix (typos, bugs with obvious solution), please open an issue first.
If the edited files were covered by tests, updated tests are required for merging. Please look into the tests folders and make sure you cover new code.
- Fixes ... #746 
- Tests: ... yes
- Docs updated: ... yes
If applicable, briefly describe how the issue was addressed.
=> Set accurate fps if possible

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, docs/_docs/runtime-permissions.md
- Fixes #774 
- Tests: no
I added setter for auto checks permissions flag.
=> Add setter for flag enabled/disabled auto check permissions

.github/workflows/build.yml, README.md, cameraview/build.gradle, docs/_about/changelog.md, docs/_config.yml
=> Release v2.6.2

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
- Fixes #763
- Tests: no
Allowed pass null to setLifecycleOwner
=> Add ability clear lifecycleObserver

cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java
- Fixes #896
- Tests: no
I wrapped this crashes, because I want notify my app that camera has problem and I can show users that camera has problem and users can continue use other feature in app without crashes.
=> Wrapped some crashes which connect with params

.github/workflows/build.yml, .github/workflows/deploy.yml, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java
=> Add CameraEngine.getRepeatingRequestDefaultTemplate

cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/orchestrator/CameraOrchestrator.java, cameraview/src/main/java/com/otaliastudios/cameraview/internal/FpsRangeValidator.java, demo/src/main/kotlin/com/otaliastudios/cameraview/demo/CameraActivity.kt
- Fix preview on Pixel 4 when using certain FPS values
- Fix deadlock when using surface preview
=> Fix preview on Pixel devices, fix deadlock with surface preview

cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java
=> Make filterFrameRateRanges protected

cameraview/src/main/java/com/otaliastudios/cameraview/CameraListener.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/gesture/GestureAction.java, cameraview/src/main/res/values/attrs.xml, demo/src/main/kotlin/com/otaliastudios/cameraview/demo/CameraActivity.kt
* Added Swipe Left and Right callback on CameraListener.
* Added Shutter event callback on CameraListener.
* Updated Demo with new callbacks implemented.
=> Implement Swipe and Shutter callback. Add GestureAction.TAKE_PICTURE_SNAPSHOT.

.github/workflows/build.yml, README.md, build.gradle.kts, cameraview/build.gradle.kts, cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewCallbacksTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraListener.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java, cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java, docs/_about/changelog.md, docs/_config.yml, docs/_docs/capturing-media.md, docs/_docs/gestures.md, gradle/wrapper/gradle-wrapper.properties
=> Release v2.7.0

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java, cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java, cameraview/src/main/res/values/attrs.xml
https://github.com/natario1/CameraView/issues/1067
Added the attribute:
- `cameraGesturesEnabled`
Added the APIs:
- `setGesturesEnabled(boolean);`
- `getGesturesEnabled();`
=> Add flag to disable automatic gesture handling

.github/workflows/build.yml, .github/workflows/snapshot.yml, LICENSE, README.md, build.gradle.kts, cameraview/build.gradle.kts, cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java, demo/build.gradle.kts, docs/_about/changelog.md, docs/_about/faq.md, docs/_about/install.md, docs/_config.yml, docs/_extra/contributing.md, gradle/wrapper/gradle-wrapper.properties
- Publish on Maven Central
- Don't crash on configureFailed
=> Release 2.7.1
