natario1/CameraView

README.md
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraLoggerTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/utils/com/otaliastudios/cameraview/CameraLogger.java
cameraview/src/main/views/com/otaliastudios/cameraview/ScrollGestureLayout.java
codecov.yml
demo/src/main/java/com/otaliastudios/cameraview/demo/MainActivity.java

This tool might be helpful for debugging issues.
Can be controlled with `CameraLogger.setLogLevel()`. By default will show only errors, so no floods to your logcat.

Add logger for debugging

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/WorkerHandlerTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/utils/com/otaliastudios/cameraview/WorkerHandler.java
demo/src/main/AndroidManifest.xml

Have handlers survive config changes so start() and stop() calls are streamlined. Fixes #28 .

WorkerHandler survives config changes

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/views/com/otaliastudios/cameraview/SurfaceViewPreview.java

TextureView won't work when hardware acceleration is off for some reason.
Fallback to our other preview implementation.

Use SurfaceViewPreview when hardware acceleration is off

---

README.md
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java

Setting audio to `Audio.OFF` will let you use the library without audio permission.

Dont require AUDIO permission if audio is OFF

---

README.md
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/res/values/attrs.xml

Lets you choose whether to play sound effects. 
Camera1 will always play the shutter sound no matter this flag. But Camera2 won't have this issue.
Fixes #34

Add playSounds control

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraUtilsTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java
cameraview/src/main/utils/com/otaliastudios/cameraview/CameraUtils.java
cameraview/src/main/utils/com/otaliastudios/cameraview/CropHelper.java
demo/src/main/java/com/otaliastudios/cameraview/demo/PicturePreviewActivity.java
demo/src/main/res/layout/activity_picture_preview.xml

You can now pass maxWidth and maxHeight to decodeBitmap.
Fixes #76 
Fixes #12

Improve CameraUtils.decodeBitmap

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java

I verified this fixes the memory leak because I can no longer trigger it with Leakcanary in my app.
One thing I'm a bit concerned about is that `stopImmeditely()` is currently only called from `CameraView.destroy()`, so this codes works when the user wants to destroy the camera permanently, but if a user tries to `start()` the camera again, the `UncaughtExceptionHandler` won't be restored.
Should we be restoring / setting the `UncaughtExceptionHandler` in `start()`?

Fixes #90 Remove UncaughtExceptionHandler from CameraController in stopImmediately

---

cameraview/src/main/utils/com/otaliastudios/cameraview/CropHelper.java

https://github.com/natario1/CameraView/issues/91
Reduced memory usage to avoid any OOM.
Library could lead to OOM due to the huge amount of memory allocated by the bitmap.
(Java memory increases up to 60 MB, sometimes up to 100 MB!)
Memory usage reduced and released the bitmap memory allocated.
(Java memory increases from 17 MB to 25 MB only)
See reviewer section.

Reduced memory usage to avoid any OOM.

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraCallbacksTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/Frame.java
cameraview/src/main/java/com/otaliastudios/cameraview/FrameManager.java
cameraview/src/test/java/com/otaliastudios/cameraview/FrameManagerTest.java
cameraview/src/test/java/com/otaliastudios/cameraview/FrameTest.java

Fixes #87 , should give a huge improvement in memory consumption and efficiency.
Both byte buffers and `Frame` instances are automatically recycled, with small impact on who's not using processors at all.

Improve frame processing - recycle buffers and Frame instances

---

README.md
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraCallbacksTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraUtilsTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewCallbacksTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/PreviewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/WorkerHandlerTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraException.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraListener.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/utils/com/otaliastudios/cameraview/Task.java
cameraview/src/test/java/com/otaliastudios/cameraview/CameraExceptionTest.java

- Make CameraView completely thread-safe
- All actions are posted to a single thread, like Camera1 docs suggest
- This should avoid any "used after release" error
- Add `CameraListener.onCameraError()` and `CameraException` for unrecoverable errors
- Fix some bugs with video recording and MediaRecorder not correctly setup or released
Fixes #77 
Fixes #61

Make CameraView thread-safe

---

README.md
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/AspectRatio.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/Size.java
cameraview/src/main/java/com/otaliastudios/cameraview/SizeSelector.java
cameraview/src/main/java/com/otaliastudios/cameraview/SizeSelectors.java
cameraview/src/main/options/com/otaliastudios/cameraview/SessionType.java
cameraview/src/main/res/values/attrs.xml
cameraview/src/test/java/com/otaliastudios/cameraview/AspectRatioTest.java
cameraview/src/test/java/com/otaliastudios/cameraview/SizeSelectorsTest.java
cameraview/src/test/java/com/otaliastudios/cameraview/SizeTest.java
demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java
demo/src/main/res/layout/activity_camera.xml

- Deprecate `toggleFlash`, was broken after #97 
- Deprecate `getCaptureSize()`, replaced with `getPictureSize()`
- Add `cameraView.setPictureSize(SizeSelector)` to choose the output JPEG size
- Add lots of handy size selectors in the `SizeSelectors` class, to apply easy constraints. minWidth, maxWidth, minHeight, maxHeight, minArea, maxArea, smallest, biggest, aspectRatio
- Merge and join selectors with `SizeSelectors.and()` and `SizeSelectors.or()`, very useful
- Add XML attributes for all of this
Closes #49

Add option to choose the picture output size

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraOptions1Test.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraListener.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/options/com/otaliastudios/cameraview/Audio.java
cameraview/src/main/options/com/otaliastudios/cameraview/Control.java
cameraview/src/main/options/com/otaliastudios/cameraview/Facing.java
cameraview/src/main/options/com/otaliastudios/cameraview/Flash.java
cameraview/src/main/options/com/otaliastudios/cameraview/Grid.java
cameraview/src/main/options/com/otaliastudios/cameraview/Hdr.java
cameraview/src/main/options/com/otaliastudios/cameraview/SessionType.java
cameraview/src/main/options/com/otaliastudios/cameraview/VideoQuality.java
cameraview/src/main/options/com/otaliastudios/cameraview/WhiteBalance.java
demo/src/main/java/com/otaliastudios/cameraview/demo/Control.java

`VideoQuality`, `Hdr`, `Grid`, `SessionType`, `Audio`, `WhiteBalance`, `Flash` and `Facing` now extend a base `Control` interface.
This brings 
- easy methods to set the camera state (`cameraView.set(Control)`)
- easy methods to check for availability (`cameraOptions.supports(Control)` and `cameraOptions.getSupportedControls(Class<T extends Control>)`.

Add base Control class, add easy setters and CameraOptions APIs

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java

This should fix #108 and possibly not break anything else.
The old formula was giving correct results for `sensorOffset = 90` and `sensorOffset = 270`, but not in the other cases (`0` and `180`). That might be the reason why no-one has been reporting it.

Change the offset computation for front cameras

---

README.md
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewCallbacksTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraListener.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/res/values/attrs.xml
demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java

Hello, 
I had a need to set a max file size limit for my implementation of the camera and added the API to set a limit. I added a new API method `setMaxFileSize(long maxFileSizeInBytes)` to set a custom maximum file size for a video recording. The camera ignores the max file size if its not set or is invalid. 
I added another boolean parameter to the video callback method indicating if the video ended due to a file size limit. I also included a helper getter method to get the status of the current camera video recording. It felt easier as I could rely on `cameraView.isRecordingVideo()` instead of having my own boolean tracking in my activity.
Thanks!

Max video file size

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java

matchRatio may get unexpected size when implementation of getSupportedPreviewSizes() decides to return values in a non-descending order.

fix preview size selection

---

build.gradle
cameraview/build.gradle
demo/build.gradle
gradle/wrapper/gradle-wrapper.properties

I migrated to the new Android Gradle plugin to not longer leak the dependencies. With the old plugin you get a warning about different support library versions:
More Info: [Migrate to Android Plugin for Gradle 3.0.0](https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html)

Migrate to new Android Gradle plugin

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera2.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java

On some devices even if playSounds = "false" the shutter sound is still played. This pull request handles this issue on those devices where it's possible to mute programmatically:  
`if (info.canDisableShutterSound)`

Fix camera mute

---

README.md
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/MapperTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/Mapper.java
cameraview/src/main/options/com/otaliastudios/cameraview/VideoCodec.java
cameraview/src/main/res/values/attrs.xml

Let you choose the encoding format. Fixes #136

Add VideoCodec option

---

cameraview/src/main/java/com/otaliastudios/cameraview/FrameManager.java

Removing the +1 in order to solve the mismatch between frame size and data size.

Removed +1 from frame byte return

---

CHANGELOG.md
README.md
build.gradle
cameraview/build.gradle
cameraview/src/main/views/com/otaliastudios/cameraview/ScrollGestureLayout.java
gradle/wrapper/gradle-wrapper.properties

- Fixes #180 
- Fixes #191 
- Update to 1.5.1

Bump version

---

cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java

Fixed Exception on some devices when we use default videoCodec instead CamcorderProfile videoCodec.
I had exception on Sony D5503 (API 22) in demo.
Issue GH-233

Fixed issue #233. Exception on some devices when we use default videoCodec.

---

.travis.yml
README.md
build.gradle
cameraview/build.gradle
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraException.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
demo/build.gradle
demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java

- Update dependencies and android to v. 28
- Added `CameraException.getReason()` to know more about what has failed and why
- Catching exceptions for `Camera.open()` and `Camera.startPreview()` so app does not crash
- Implement `LifecycleObserver` to remove start, stop and destroy boilerplate

Error handling and lifecycle boilerplate

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/OrientationHelperTest.java
cameraview/src/main/utils/com/otaliastudios/cameraview/OrientationHelper.java

It is better to use a previous orientation value when a sensor returns ORIENTATION_UNKNOWN.
It will allow to make landscape photos when a device is almost parallel to the ground plane.

Fix OrientationHelper

---

cameraview/src/main/res/layout/cameraview_texture_view.xml

solution from here - https://stackoverflow.com/a/47796036
Without this fix library throws "java.lang.UnsupportedOperationException: TextureView doesn't support displaying a background drawable" on target sdk 28

Fixed bug with deprecated method setBackgroundDrawable

---

cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java

Fix for [autoFocus failed in tablets #181](https://github.com/natario1/CameraView/issues/181)
The tldr version is that some devices (including Galaxy Tab A 7.0" 2016 and lots of Sony phones like Xperia Z, Z1, V, ...) occasionally throw Runtime exceptions when calling autoFocus.
It doesn't seem that we can do much about. So, let's at least handle the exception and prevent the crash and user can trigger the focus later if required.

Handle autoFocus exceptions (issue #181)

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraPreviewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/IntegrationTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/MockCameraController.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/TextureCameraPreviewTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/SnapshotPictureRecorder.java
cameraview/src/main/res/values/attrs.xml
cameraview/src/main/views/com/otaliastudios/cameraview/CameraPreview.java
cameraview/src/main/views/com/otaliastudios/cameraview/GlCameraPreview.java
cameraview/src/main/views/com/otaliastudios/cameraview/SurfaceCameraPreview.java
cameraview/src/main/views/com/otaliastudios/cameraview/TextureCameraPreview.java
demo/src/main/java/com/otaliastudios/cameraview/demo/PicturePreviewActivity.java
demo/src/main/java/com/otaliastudios/cameraview/demo/VideoPreviewActivity.java
docs/_posts/2018-12-20-capture-size.md
docs/_posts/2018-12-20-capturing-media.md
docs/_posts/2018-12-20-debugging.md
docs/_posts/2018-12-20-error-handling.md
docs/_posts/2018-12-20-more-features.md
docs/_posts/2018-12-20-preview-size.md
docs/_posts/2018-12-20-runtime-permissions.md
docs/_posts/2019-02-24-snapshot-size.md

- Renames `setPreviewSize` to `setPreviewStreamSize` (sorry). `previewSize` made people think it is related to the view size but it's not.
- New APIs: `setSnapshotMaxWidth` and `setSnapshotMaxHeight`.
These are very useful in that they separate the snapshot size from the preview stream size. You can have a big preview stream size so that the preview is pleasant to the eye.
Then apply `maxWidth` and `maxHeight` constraints for snapshots. If the snapshot size is bigger than your constraints, the snapshot will be downscaled to match them.
This makes you have a good looking preview and take low-res videos & pictures.

New snapshot max size APIs

---

cameraview/src/main/views/com/otaliastudios/cameraview/GlCameraPreview.java

Remove old logic that was just unneeded and caused recreating the gl surface when CameraView changes dimensions.

Make CameraPreview faster

---

cameraview/src/main/java/com/otaliastudios/cameraview/Camera1.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraController.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/res/values/attrs.xml
docs/_posts/2018-12-20-more-features.md

Certain devices with low-end cameras are slow to perform auto-focus.  My changes add an additional parameter to startAutoFocus which will suppress the reset of auto-focus which will retain the current focus for future usages (scans, pictures, ...)

Added setAutoFocusResetDelay to api to control autofocus reset options

---

cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java

we were facing the delay in the callback for video record start in few devices this PR contains the fix for the same
- Tests: ... no
- Docs updated: ... *no*
As discussed, moved the video start callback in SnapshotVideoRecorder from onEncodingStart to onStart. Since onStart gets called a bit early, the performance is better.

Fix for Video Start Callback delay

---

.github/workflows/build.yml
.github/workflows/deploy.yml
cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/Camera2IntegrationTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/CameraIntegrationTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/MockCameraEngine.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/frame/ByteBufferFrameManagerTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/frame/FrameManagerTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/action/LogAction.java
cameraview/src/main/java/com/otaliastudios/cameraview/frame/FrameManager.java
cameraview/src/main/res/values/attrs.xml
docs/_posts/2018-12-20-frame-processing.md
docs/css/main.css

- New: `setFrameProcessingPoolSize()`: the number of Frames that can exist at any given moment
- New: `setFrameProcessingExecutors()`: the number of threads involved in Frame processing
The pool size should always be = number of executors + 1.

Frame processing threading APIs

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/VideoResultTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/VideoResult.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java
cameraview/src/main/java/com/otaliastudios/cameraview/video/FullVideoRecorder.java
docs/_docs/capturing-media.md

Added support to save video recording to FileDescriptor using takeVideo(). Didn't update takeVideoSnapshot() since it uses MediaMuxer which has support for FileDescriptor from [API 26 only](https://developer.android.com/reference/android/media/MediaMuxer#MediaMuxer(java.io.FileDescriptor,%20int)).
- Fixes #461
- Tests: no
- Docs updated: yes

Add support to record video to FileDescriptor.

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraLogger.java

- Fixes #778
- Tests: no
Replace `List` on `thread safe Set` for CameraLogger listeners.

Thread safe CameraLogger

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/VideoResultTest.java
cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/options/Camera1OptionsTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraOptions.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/VideoResult.java
cameraview/src/main/java/com/otaliastudios/cameraview/controls/AudioCodec.java
cameraview/src/main/java/com/otaliastudios/cameraview/controls/ControlParser.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraEngine.java
cameraview/src/main/java/com/otaliastudios/cameraview/video/FullVideoRecorder.java
cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java
cameraview/src/main/res/values/attrs.xml
demo/src/main/java/com/otaliastudios/cameraview/demo/CameraActivity.java
demo/src/main/java/com/otaliastudios/cameraview/demo/Option.java
demo/src/main/java/com/otaliastudios/cameraview/demo/VideoPreviewActivity.java
demo/src/main/res/layout/activity_video_preview.xml
docs/_docs/controls.md

- Fixes ... (#860 )
- Tests: ... (yes)
- Docs updated: ... (yes)
I followed the path of setting video codec as closely as I could. Adding `AudioCodec` as a control that can be set on `CameraView`. When `CameraBaseEngine#takeVideo` or `CameraBaseEngine#takeVideoSnapshot` are called, they set the codec on the `VideoResult.Stub` object. Later on in the flow, `FullVideoRecorder` will set any audio codec that isn't default on the `CamcorderProfile` object which is in turn used to set `audioType` and get the encoders.
One possible source of contention that I can see is the management of minimum sdk for some of the codecs. Open to ideas on this though.

Add capability to set audio codec to encode video files with.

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/engine/CameraIntegrationTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/picture/Full1PictureRecorder.java

- Fixes #824 
- Tests: No tests existed for the only edited class, `Full1PictureRecorder`
- Docs updated: No, fixes behind the scenes bug
Took solution from @natario1 's comment on issue, simply needed to re-setup the frame manager after capturing a photo

Restart Camera1 Frame Processing After Taking a Picture - Fixes Issue 824

---

cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java

- Fixes: #850
- Tests: no
I wrapped in tryCatch these problem places.

Wrapped some crashes happened when start camera

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/internal/OrientationHelper.java

- Fixes 927
- Tests: no
Added boolean to prevent listener activating multiple times.
Added a call in CameraView onPause to disable OrientationHelper

Fix for #927 OrientationHelper.enable() called twice

---

cameraview/build.gradle.kts
cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/orchestrator/CameraOrchestrator.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/orchestrator/CameraStateOrchestrator.java

Rewrites CameraOrchestrator to avoid stack overflows, adds new internal `trim()`behavior for high frequency API calls like zoom and EV.

Rewrite orchestrator 

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraUtils.java

One trivial line that would had saved me a couple of hours.
Writing the image to file may fail for reasons that are not always obvious.
In my case the directory did not always exist
Having a log with the cause can be really helpfull

Log errors when writing the image to a file

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraUtils.java
cameraview/src/main/java/com/otaliastudios/cameraview/picture/Full1PictureRecorder.java
cameraview/src/main/java/com/otaliastudios/cameraview/picture/Full2PictureRecorder.java

- Fixes issue: https://github.com/natario1/CameraView/issues/1023
- Tests: no
We were seeing a crash when the camera hardware failed to take a picture. We would like to see the exception handled or handleable at least, so that the app can remain running the and app can choose what the correct behavior should be (i.e. show error dialog, continue along flow, etc.)

add try catch to catch exceptions when takePicture fails

---

cameraview/src/androidTest/java/com/otaliastudios/cameraview/CameraViewTest.java
cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/overlay/Overlay.java
cameraview/src/main/java/com/otaliastudios/cameraview/overlay/OverlayDrawer.java
cameraview/src/main/java/com/otaliastudios/cameraview/overlay/OverlayLayout.java
cameraview/src/main/res/values/attrs.xml
docs/_docs/watermarks-and-overlays.md

https://github.com/natario1/CameraView/issues/1065
Added the attribute:
- `cameraOverlayHardwareCanvas`
Added the APIs:
- `setOverlayHardwareCanvasEnabled(boolean on);`
- `getOverlayHardwareCanvasEnabled();`
**Note:** `lockHardwareCanvas` is only available in API 23+

Add option to capture hardware accelerated overlays

---

cameraview/src/main/java/com/otaliastudios/cameraview/internal/FpsRangeValidator.java

Unless this is a simple fix (typos, bugs with obvious solution), please open an issue first so that
we can discuss the best approach to address the problem. Without a reference issue and discussion, 
unfortunately, this PR will likely be ignored.
If the edited files were covered by tests, updated tests are required for merging. 
Please look into the tests folders and make sure you cover new code.
- Fixes ... (*1088*)
- Tests: ... (*no*)
- Docs updated: ... (*no*)
'Pixel 4a' added to list of problematic devices in FpsRangeValidator

#1088: add Pixel 4a into FpsRangeValidator

---

cameraview/src/main/java/com/otaliastudios/cameraview/CameraView.java
cameraview/src/main/java/com/otaliastudios/cameraview/internal/OrientationHelper.java
cameraview/src/main/java/com/otaliastudios/cameraview/preview/SurfaceCameraPreview.java

This is going to happen with compose apps.

Fix orientation when activity handles rotations with android:configChanges without locking

---

cameraview/src/main/java/com/otaliastudios/cameraview/internal/FpsRangeValidator.java

Unless this is a simple fix (typos, bugs with obvious solution), please open an issue first so that
we can discuss the best approach to address the problem. Without a reference issue and discussion, 
unfortunately, this PR will likely be ignored.
If the edited files were covered by tests, updated tests are required for merging. 
Please look into the tests folders and make sure you cover new code.
- Fixes ... (*issue number*)
- Tests: ... (*yes/no*)
- Docs updated: ... (*yes/no*)
'Pixel 4XL' added to list of problematic devices in FpsRangeValidator

#1088: add Pixel 4XL into FpsRangeValidator

---

.github/pull_request_template.md
cameraview/src/main/java/com/otaliastudios/cameraview/BitmapCallback.java
cameraview/src/main/java/com/otaliastudios/cameraview/PictureResult.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera1Engine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/Camera2Engine.java
cameraview/src/main/java/com/otaliastudios/cameraview/engine/CameraBaseEngine.java
demo/src/main/kotlin/com/otaliastudios/cameraview/demo/PicturePreviewActivity.kt
docs/_docs/capturing-media.md
docs/_docs/filters.md
docs/_docs/frame-processing.md
docs/_docs/metering.md
docs/_docs/preview-size.md
docs/_extra/v1-migration-guide.md

Unless this is a simple fix (typos, bugs with obvious solution), please open an issue first so that
we can discuss the best approach to address the problem. Without a reference issue and discussion, 
unfortunately, this PR will likely be ignored.
If the edited files were covered by tests, updated tests are required for merging. 
Please look into the tests folders and make sure you cover new code.
- Fixes: #1175 #1168
- Tests: no
- Docs updated: yes
The exception in #1175 was simply wrapped in a try-catch block with a `CameraException` thrown from there.
Both exceptions in #1168 are now prevented early with a null check - `getData()` method now never returns `null` in a normal flow of execution (when no exceptions are dispatched).

A couple of fixes and docs improvements

---

cameraview/src/main/java/com/otaliastudios/cameraview/video/SnapshotVideoRecorder.java

Hi, @natario1. `setSize` requires a width and a height, but the line passes two widths. Usually, this wouldn't cause a problem, but the video size would be wrong when taking a snapshot video with a MultiFilter.
Issue #837 mentioned something similar.

Fix the setSize typo in SnapshotVideoRecorder
